SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS
left join ANIMAL_OUTS
on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE like "%Intact%"
AND (ANIMAL_OUTS.SEX_UPON_OUTCOME like "%Neutered%" OR
     ANIMAL_OUTS.SEX_UPON_OUTCOME like "%Spayed%")