SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME 
from ANIMAL_OUTS
left join ANIMAL_INS
on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID 
where ANIMAL_INS.ANIMAL_ID is NULL

#SELECT A.ANIMAL_ID, A.NAME 
#FROM ANIMAL_OUTS A left join ANIMAL_INS B
#on A.ANIMAL_ID = B.ANIMAL_ID
#WHERE B.ANIMAL_ID is NULL